# Generated by Django 4.0.5 on 2022-06-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Training', 'Training'), ('PT Assessment', 'PT Assessment')], max_length=50)),
                ('embedded_url', models.URLField()),
            ],
        ),
    ]
