# Generated by Django 4.0.5 on 2022-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='embedded_url',
            field=models.CharField(max_length=500),
        ),
    ]
