# Generated by Django 4.0.5 on 2022-12-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_description_alter_video_embedded_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('PT Assessment', 'PT Assessment'), ('Unit', 'Unit'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
