# Generated by Django 4.0.5 on 2022-06-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('AB', 'AB'), ('AMN', 'AMN'), ('A1C', 'A1C'), ('SRA', 'SRA'), ('SSGT', 'SSGT'), ('TSGT', 'TSGT'), ('MSGT', 'MSGT'), ('SMSGT', 'SMSGT'), ('CMSGT', 'CMSGT'), ('2LT', '2LT'), ('1LT', '1LT'), ('CAPT', 'CAPT'), ('MAJ', 'MAJ'), ('LT COL', 'LT COL'), ('COL', 'COL'), ('BRIG GEN', 'BRIG GEN'), ('MAJ GEN', 'MAJ GEN'), ('LT GEN', 'LT GEN'), ('GEN', 'GEN')], default='AB', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
        ),
    ]
