# Generated by Django 4.0.5 on 2022-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('document_created', models.DateTimeField(auto_now_add=True)),
                ('document_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
