# Generated by Django 4.0.5 on 2022-06-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(blank=True, choices=[('Appointment Letter', 'Appointment Letter'), ('Google Form', 'Google Form'), ('Information', 'Information'), ('PT Form', 'PT Form')], max_length=50, null=True),
        ),
    ]
