# Generated by Django 4.0.5 on 2022-07-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedded_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
