# Generated by Django 4.0.5 on 2022-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='embedded_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
