# Generated by Django 4.0.5 on 2022-06-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('AB', 'AB'), ('AMN', 'AMN'), ('A1C', 'A1C'), ('SRA', 'SRA'), ('SSGT', 'SSGT'), ('TSGT', 'TSGT'), ('MSGT', 'MSGT'), ('SMSGT', 'SMSGT'), ('CMSGT', 'CMSGT'), ('2LT', '2LT'), ('1LT', '1LT'), ('CAPT', 'CAPT'), ('MAJ', 'MAJ'), ('LT COL', 'LT COL'), ('COL', 'COL'), ('BRIG GEN', 'BRIG GEN'), ('MAJ GEN', 'MAJ GEN'), ('LT GEN', 'LT GEN'), ('GEN', 'GEN')], default='AB', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalTrainingLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpr_card', models.URLField(verbose_name='CPR Card')),
                ('ptl_completion_date', models.DateField(blank=True, null=True, verbose_name='PTL Completion Date')),
                ('appointment_letter', models.URLField(verbose_name='Appointment Letter')),
                ('airman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'PTL',
                'verbose_name_plural': 'PTL Team',
            },
        ),
        migrations.CreateModel(
            name='UnitFitnessProgramManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufpm_completion_date', models.DateField(blank=True, null=True, verbose_name='UFPM Completion Date')),
                ('appointment_letter', models.URLField(verbose_name='Appointment Letter')),
                ('written_order', models.URLField(verbose_name='MyFitness Written Order')),
                ('airman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'UFPM',
                'verbose_name_plural': 'UFPM Team',
            },
        ),
        migrations.CreateModel(
            name='UnitFitnessAssessmentCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufac_completion_date', models.DateField(blank=True, null=True, verbose_name='UFAC Completion Date')),
                ('system_authorization_request', models.URLField(verbose_name='DD Form 2875 - System Authorization Request')),
                ('written_order', models.URLField(verbose_name='MyFitness Written Order')),
                ('user_agreement', models.URLField(verbose_name='MyFitness User Agreement')),
                ('physical_training_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.physicaltrainingleader', verbose_name='PTL')),
            ],
            options={
                'verbose_name': 'Unit Fitness Assessment Cell',
                'verbose_name_plural': 'Unit Fitness Assessment Cell Team',
            },
        ),
    ]
