# Generated by Django 4.0.5 on 2022-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicaltrainingleader',
            options={'ordering': ['-cpr_expiration_date', 'last_name'], 'verbose_name': 'PTL', 'verbose_name_plural': 'Physical Training Leader Team'},
        ),
        migrations.AddField(
            model_name='physicaltrainingleader',
            name='cpr_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='CPR Expiration Date'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone #'),
        ),
    ]
