# Generated by Django 4.0.5 on 2022-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaltrainingleader',
            name='appointment_letter',
            field=models.URLField(verbose_name='Appointment Letter URL'),
        ),
        migrations.AlterField(
            model_name='physicaltrainingleader',
            name='cpr_card',
            field=models.URLField(verbose_name='CPR Card URL'),
        ),
        migrations.AlterField(
            model_name='unitfitnessassessmentcell',
            name='system_authorization_request',
            field=models.URLField(verbose_name='DD Form 2875 - System Authorization Request URL'),
        ),
        migrations.AlterField(
            model_name='unitfitnessassessmentcell',
            name='user_agreement',
            field=models.URLField(verbose_name='MyFitness User Agreement URL'),
        ),
        migrations.AlterField(
            model_name='unitfitnessassessmentcell',
            name='written_order',
            field=models.URLField(verbose_name='MyFitness Written Order URL'),
        ),
        migrations.AlterField(
            model_name='unitfitnessprogrammanager',
            name='appointment_letter',
            field=models.URLField(verbose_name='Appointment Letter URL'),
        ),
        migrations.AlterField(
            model_name='unitfitnessprogrammanager',
            name='written_order',
            field=models.URLField(verbose_name='MyFitness Written Order URL'),
        ),
    ]
