# Generated by Django 4.0.5 on 2022-12-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_physicaltrainingleader_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicaltrainingleader',
            options={'ordering': ['cpr_expiration_date', 'last_name'], 'verbose_name': 'PTL', 'verbose_name_plural': 'Physical Training Leader Team'},
        ),
    ]
