# Generated by Django 4.0.5 on 2023-01-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_specialmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialmember',
            options={'verbose_name': 'Special Member', 'verbose_name_plural': 'Special Members'},
        ),
        migrations.RenameField(
            model_name='specialmember',
            old_name='description',
            new_name='comment',
        ),
    ]
